// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SummaryAndCheck.Models;

#nullable disable

namespace SummaryAndCheck.Models.Migrations
{
    [DbContext(typeof(SummaryAndCheckDbContext))]
    [Migration("20260206075629_UpdatePasskeyStorage")]
    partial class UpdatePasskeyStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SummaryAndCheck.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<byte[]>("StoredCredential")
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.CreditHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("HistoryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HistoryType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueChanged")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId");

                    b.ToTable("CreditHistory", (string)null);

                    b.HasDiscriminator<int>("HistoryType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SummaryAndCheck.Models.DiscordUser", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Credit")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastFreeUse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("DiscordUser", (string)null);
                });

            modelBuilder.Entity("SummaryAndCheck.Models.DiscordUserAccountBinding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DiscordUserAccountBinding", (string)null);
                });

            modelBuilder.Entity("SummaryAndCheck.Models.PasskeyStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SignCount")
                        .HasColumnType("integer");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PasskeyStorage");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.StoredAuthenticationOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Challenge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoredAuthenticationOptions");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.StoredRegistrationOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Challenge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoredRegistrationOptions");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.SystemConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfig", (string)null);
                });

            modelBuilder.Entity("SummaryAndCheck.Models.CreditAdminHistory", b =>
                {
                    b.HasBaseType("SummaryAndCheck.Models.CreditHistory");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("SummaryAndCheck.Models.CreditTopUpHistory", b =>
                {
                    b.HasBaseType("SummaryAndCheck.Models.CreditHistory");

                    b.Property<long>("AccountBindingId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasIndex("AccountBindingId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("SummaryAndCheck.Models.CreditUseHistory", b =>
                {
                    b.HasBaseType("SummaryAndCheck.Models.CreditHistory");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ServerId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("UseType")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SummaryAndCheck.Models.CreditHistory", b =>
                {
                    b.HasOne("SummaryAndCheck.Models.DiscordUser", "DiscordUser")
                        .WithMany("CreditHistories")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordUser");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.CreditTopUpHistory", b =>
                {
                    b.HasOne("SummaryAndCheck.Models.DiscordUserAccountBinding", "AccountBinding")
                        .WithMany("CreditTopUpHistories")
                        .HasForeignKey("AccountBindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountBinding");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.DiscordUser", b =>
                {
                    b.Navigation("CreditHistories");
                });

            modelBuilder.Entity("SummaryAndCheck.Models.DiscordUserAccountBinding", b =>
                {
                    b.Navigation("CreditTopUpHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
